# Generated by Django 2.1.5 on 2020-09-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
    ]
