# Generated by Django 2.1.5 on 2020-09-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200904_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.IntegerField(default=-1, unique=True)),
                ('teacherID', models.CharField(default='', max_length=128)),
                ('courseID', models.CharField(default='', max_length=128, unique=True)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(default='', max_length=128, unique=True)),
                ('courseName', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
