# Generated by Django 2.1.5 on 2020-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_classprofile_numofstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='belongingClass',
            field=models.CharField(default='', max_length=128),
        ),
    ]
