# Generated by Django 2.1.5 on 2020-09-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_studentprofile_belongingclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classprofile',
            name='courseID',
            field=models.CharField(default='', max_length=128),
        ),
    ]
