# Generated by Django 2.1.5 on 2020-09-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20200906_0941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceprofile',
            unique_together={('classID', 'studentID')},
        ),
    ]
