# Generated by Django 2.1.5 on 2020-09-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20200906_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceprofile',
            name='classID',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='attendanceprofile',
            name='studentID',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='classprofile',
            name='courseID',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='classprofile',
            name='teacherID',
            field=models.CharField(default='', max_length=128),
        ),
    ]
