# Generated by Django 2.1.5 on 2020-09-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20200918_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='classprofile',
            name='belongingClass',
            field=models.CharField(default='class1', max_length=128),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='belongingClass',
            field=models.CharField(default='class1', max_length=128),
        ),
    ]
